[package]
name = "webrip"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[lib]
name = "webrip_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "webrip"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-http = "2"
tauri-plugin-cors-fetch = "2.1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# This feature is used for production builds or when `devPath` points to the production build of your frontend
custom-protocol = ["tauri/custom-protocol"]

